// How to edit content: adjust the projects array to change gallery items, titles, tags, and image URLs.

export const projects = [
  {
    id: "p1",
    //title: "Bedroom Room Refresh",
    location: "London, ON",
    // tag: "Before → After",
    afterSrc:"/public/work/1.jpeg",
  },
  {
    id: "p2",
    //title: "Modern Hallway",
    location: "London, ON",
    tag: "Work",
    afterSrc:"/public/work/Sample_2.jpg",
  },
  {
    id: "p3",
    //title: "Kitchen Cabinet Refinish",
    location: "North London",
    afterSrc:"/public/work/2.jpeg",
    
  },
  {
    id: "p4",
    //title: "Staircase & Trim",
    location: "Komoka, ON",
    tag: "Before → After",
    afterSrc:"/public/work/project-01-after.jpg",
    beforeSrc:"/public/work/project-01-before.jpg",
  },
  {
    id: "p5",
    //title: "Primary Bedroom",
    location: "North London",
    //tag: "Before → After",
    afterSrc:"/public/work/3.jpeg",
    
  },
  {
    id: "p6",
    //title: "Exterior Entry",
    location: "London, ON",
    tag: "Work",
    afterSrc:"/public/work/5.jpeg",
  },
  {
    id: "p7",
    //title: "Dining Room",
    location: "London, ON",
    tag: "Before → After",
    afterSrc:"/public/work/36_After.jpg",
    beforeSrc:"/public/work/36_Before.jpg",
  },
  {
    id: "p8",
    //title: "Basement Finish",
    location: "Dorchester, ON",
    tag: "Before → After",
    afterSrc:"/public/work/17_After.jpg",
    beforeSrc:"/public/work/17_Before.jpg",
  },
  {
    id: "p9",
    //title: "Crisp White Trim",
    location: "London, ON",
    tag: "Before → After",
    afterSrc:"/public/work/18_After.jpg",
    beforeSrc:"/public/work/18_Before.jpg",
  },
  {
    id: "p10",
    //title: "Crisp White Trim",
    location: "London, ON",
    tag: "Before → After",
    afterSrc:"/public/work/20_After.jpg",
    beforeSrc:"/public/work/20_Before.jpg",
  },
  {
    id: "p11",
    //title: "Crisp White Trim",
    location: "London, ON",
    tag: "Work",
    afterSrc:"/public/work/42.jpg",
  },
  {
    id: "p12",
    //title: "Crisp White Trim",
    location: "London, ON",
    tag: "Before → After",
    afterSrc:"/public/work/35_After.jpg",
    beforeSrc:"/public/work/35_Before.jpg",
  },
  {
    id: "p13",
    //title: "Crisp White Trim",
    location: "London, ON",
    tag: "Before → After",
    afterSrc:"/public/work/27_After.jpg",
    beforeSrc:"/public/work/26_Before.jpg",
  },
  {
    id: "p14",
    //title: "Crisp White Trim",
    location: "London, ON",
    tag: "Before → After",
    afterSrc:"/public/work/29_After.jpg",
    beforeSrc:"/public/work/29_Before.jpg",
  },
  {
    id: "p15",
    //title: "Crisp White Trim",
    location: "London, ON",
    tag: "Before → After",
    afterSrc:"/public/work/33_After.jpg",
    beforeSrc:"/public/work/33_Before.jpg",
  },
  {
    id: "p16",
    //title: "Crisp White Trim",
    location: "London, ON",
    tag: "Work",
    afterSrc:"/public/work/31.jpg",
  },
  {
    id: "p17",
    //title: "Crisp White Trim",
    location: "London, ON",
    tag: "Before → After",
    afterSrc:"/public/work/12_After.jpg",
    beforeSrc:"/public/work/12_Before.jpg",
  },
  {
    id: "p18",
    //title: "Crisp White Trim",
    location: "London, ON",
    tag: "Before → After",
    afterSrc:"/public/work/16_After.jpg",
    beforeSrc:"/public/work/16_Before.jpg",
  },
  {
    id: "p19",
    //title: "Crisp White Trim",
    location: "London, ON",
    tag: "Work",
    afterSrc:"/public/work/43.jpg",
    
  },
  {
    id: "p20",
    //title: "Crisp White Trim",
    location: "London, ON",
    tag: "Work",
    afterSrc:"/public/work/44.jpg",
  },
  {
    id: "p21",
    //title: "Crisp White Trim",
    location: "London, ON",
    tag: "Work",
    afterSrc:"/public/work/28.jpg",
  },
  {
    id: "p22",
    //title: "Crisp White Trim",
    location: "London, ON",
    tag: "Work",
    afterSrc:"/public/work/10.jpeg",
  },
  {
    id: "p23",
    //title: "Crisp White Trim",
    location: "London, ON",
    tag: "Work",
    afterSrc:"/public/work/16.jpg",
  },
  {
    id: "p24",
    //title: "Crisp White Trim",
    location: "London, ON",
    tag: "Before → After",
    afterSrc:"/public/work/4_After.jpg",
    beforeSrc:"/public/work/4_Before.jpg",
  },
  {
    id: "p25",
    //title: "Crisp White Trim",
    location: "London, ON",
    tag: "Work",
    afterSrc:"/public/work/40.jpg",
  },
  {
    id: "p26",
    //title: "Crisp White Trim",
    location: "London, ON",
    tag: "Work",
    afterSrc:"/public/work/41.jpg",
  },


];
